### ISSUE TITLE
How to draw a continuous vertical line？

### ISSUE THREAD

**Issue by LiuYinCarl** [laishulu/hl-fill-column#5]
This Emacs Plugin is vary useful for me to write Doc, but in files of varying line lengths, there are many broken vertical lines, so I would like to know is there any way to draw a continuous vertical line?

**Comment by laishulu** [comment]
这个我也想不到用什么机制来实现。

**Comment by laishulu** [comment]
我刚刚查了下，
新版的emacs自带了相关的mode：
`display-fill-column-indicator-mode` or `global-display-fill-column-indicator-mode`

所以现在这个package不需要了。
https://www.gnu.org/software/emacs/manual/html_node/emacs/Displaying-Boundaries.html
